# Generated by Django 5.1.6 on 2026-02-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cedant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('external_id', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cedant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='core.cedant')),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lob', models.CharField(max_length=32)),
                ('peril', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=2)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('tiv', models.DecimalField(decimal_places=2, max_digits=18)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('policy_id', models.CharField(blank=True, default='', max_length=64)),
                ('location_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='core.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Treaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('treaty_type', models.CharField(choices=[('QS', 'Quota Share'), ('XOL', 'Excess of Loss')], max_length=3)),
                ('ceded_share_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attachment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treaties', to='core.portfolio')),
            ],
        ),
    ]
