# Generated by Django 5.1.6 on 2026-03-04 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSED', 'Parsed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
